/**
 * Infoplus API
 * Infoplus API.
 *
 * OpenAPI spec version: beta
 * Contact: api@infopluscommerce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Order', 'model/PackedCarton', 'model/PackedItem', 'model/PackedMasterCarton', 'model/PackedPallet'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Order'), require('./PackedCarton'), require('./PackedItem'), require('./PackedMasterCarton'), require('./PackedPallet'));
  } else {
    // Browser globals (root is window)
    if (!root.infoplus) {
      root.infoplus = {};
    }
    root.infoplus.GetOrderPackDataOutput = factory(root.infoplus.ApiClient, root.infoplus.Order, root.infoplus.PackedCarton, root.infoplus.PackedItem, root.infoplus.PackedMasterCarton, root.infoplus.PackedPallet);
  }
}(this, function(ApiClient, Order, PackedCarton, PackedItem, PackedMasterCarton, PackedPallet) {
  'use strict';




  /**
   * The GetOrderPackDataOutput model module.
   * @module model/GetOrderPackDataOutput
   * @version beta
   */

  /**
   * Constructs a new <code>GetOrderPackDataOutput</code>.
   * @alias module:model/GetOrderPackDataOutput
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>GetOrderPackDataOutput</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GetOrderPackDataOutput} obj Optional instance to populate.
   * @return {module:model/GetOrderPackDataOutput} The populated <code>GetOrderPackDataOutput</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('orderNo')) {
        obj['orderNo'] = ApiClient.convertToType(data['orderNo'], 'String');
      }
      if (data.hasOwnProperty('order')) {
        obj['order'] = Order.constructFromObject(data['order']);
      }
      if (data.hasOwnProperty('palletList')) {
        obj['palletList'] = ApiClient.convertToType(data['palletList'], [PackedPallet]);
      }
      if (data.hasOwnProperty('masterCartonList')) {
        obj['masterCartonList'] = ApiClient.convertToType(data['masterCartonList'], [PackedMasterCarton]);
      }
      if (data.hasOwnProperty('cartonList')) {
        obj['cartonList'] = ApiClient.convertToType(data['cartonList'], [PackedCarton]);
      }
      if (data.hasOwnProperty('fullItemList')) {
        obj['fullItemList'] = ApiClient.convertToType(data['fullItemList'], [PackedItem]);
      }
      if (data.hasOwnProperty('unpackedItemList')) {
        obj['unpackedItemList'] = ApiClient.convertToType(data['unpackedItemList'], [PackedItem]);
      }
    }
    return obj;
  }

  /**
   * @member {String} orderNo
   */
  exports.prototype['orderNo'] = undefined;
  /**
   * @member {module:model/Order} order
   */
  exports.prototype['order'] = undefined;
  /**
   * @member {Array.<module:model/PackedPallet>} palletList
   */
  exports.prototype['palletList'] = undefined;
  /**
   * @member {Array.<module:model/PackedMasterCarton>} masterCartonList
   */
  exports.prototype['masterCartonList'] = undefined;
  /**
   * @member {Array.<module:model/PackedCarton>} cartonList
   */
  exports.prototype['cartonList'] = undefined;
  /**
   * @member {Array.<module:model/PackedItem>} fullItemList
   */
  exports.prototype['fullItemList'] = undefined;
  /**
   * @member {Array.<module:model/PackedItem>} unpackedItemList
   */
  exports.prototype['unpackedItemList'] = undefined;



  return exports;
}));


