/**
 * Infoplus API
 * Infoplus API.
 *
 * OpenAPI spec version: beta
 * Contact: api@infopluscommerce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.infoplus) {
      root.infoplus = {};
    }
    root.infoplus.WarehouseInventory = factory(root.infoplus.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The WarehouseInventory model module.
   * @module model/WarehouseInventory
   * @version beta
   */

  /**
   * Constructs a new <code>WarehouseInventory</code>.
   * @alias module:model/WarehouseInventory
   * @class
   */
  var exports = function() {
    var _this = this;
















































  };

  /**
   * Constructs a <code>WarehouseInventory</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WarehouseInventory} obj Optional instance to populate.
   * @return {module:model/WarehouseInventory} The populated <code>WarehouseInventory</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('sku')) {
        obj['sku'] = ApiClient.convertToType(data['sku'], 'String');
      }
      if (data.hasOwnProperty('lobId')) {
        obj['lobId'] = ApiClient.convertToType(data['lobId'], 'Number');
      }
      if (data.hasOwnProperty('warehouseId')) {
        obj['warehouseId'] = ApiClient.convertToType(data['warehouseId'], 'Number');
      }
      if (data.hasOwnProperty('onHandQuantity')) {
        obj['onHandQuantity'] = ApiClient.convertToType(data['onHandQuantity'], 'Number');
      }
      if (data.hasOwnProperty('unavailableQuantity')) {
        obj['unavailableQuantity'] = ApiClient.convertToType(data['unavailableQuantity'], 'Number');
      }
      if (data.hasOwnProperty('openPOQuantity')) {
        obj['openPOQuantity'] = ApiClient.convertToType(data['openPOQuantity'], 'Number');
      }
      if (data.hasOwnProperty('openOrderQuantity')) {
        obj['openOrderQuantity'] = ApiClient.convertToType(data['openOrderQuantity'], 'Number');
      }
      if (data.hasOwnProperty('availableQuantity')) {
        obj['availableQuantity'] = ApiClient.convertToType(data['availableQuantity'], 'Number');
      }
      if (data.hasOwnProperty('damagedQuantity')) {
        obj['damagedQuantity'] = ApiClient.convertToType(data['damagedQuantity'], 'Number');
      }
      if (data.hasOwnProperty('inFulfillmentProcessQuantity')) {
        obj['inFulfillmentProcessQuantity'] = ApiClient.convertToType(data['inFulfillmentProcessQuantity'], 'Number');
      }
      if (data.hasOwnProperty('orderableQuantity')) {
        obj['orderableQuantity'] = ApiClient.convertToType(data['orderableQuantity'], 'Number');
      }
      if (data.hasOwnProperty('unallocatableQuantity')) {
        obj['unallocatableQuantity'] = ApiClient.convertToType(data['unallocatableQuantity'], 'Number');
      }
      if (data.hasOwnProperty('daysOnHand')) {
        obj['daysOnHand'] = ApiClient.convertToType(data['daysOnHand'], 'Number');
      }
      if (data.hasOwnProperty('stockStatus')) {
        obj['stockStatus'] = ApiClient.convertToType(data['stockStatus'], 'String');
      }
      if (data.hasOwnProperty('availableQuantityCases')) {
        obj['availableQuantityCases'] = ApiClient.convertToType(data['availableQuantityCases'], 'Number');
      }
      if (data.hasOwnProperty('availableQuantityInnerPacks')) {
        obj['availableQuantityInnerPacks'] = ApiClient.convertToType(data['availableQuantityInnerPacks'], 'Number');
      }
      if (data.hasOwnProperty('availableQuantityPallets')) {
        obj['availableQuantityPallets'] = ApiClient.convertToType(data['availableQuantityPallets'], 'Number');
      }
      if (data.hasOwnProperty('damagedQuantityCases')) {
        obj['damagedQuantityCases'] = ApiClient.convertToType(data['damagedQuantityCases'], 'Number');
      }
      if (data.hasOwnProperty('damagedQuantityInnerPacks')) {
        obj['damagedQuantityInnerPacks'] = ApiClient.convertToType(data['damagedQuantityInnerPacks'], 'Number');
      }
      if (data.hasOwnProperty('damagedQuantityPallets')) {
        obj['damagedQuantityPallets'] = ApiClient.convertToType(data['damagedQuantityPallets'], 'Number');
      }
      if (data.hasOwnProperty('inFulfillmentProcessQuantityCases')) {
        obj['inFulfillmentProcessQuantityCases'] = ApiClient.convertToType(data['inFulfillmentProcessQuantityCases'], 'Number');
      }
      if (data.hasOwnProperty('inFulfillmentProcessQuantityInnerPacks')) {
        obj['inFulfillmentProcessQuantityInnerPacks'] = ApiClient.convertToType(data['inFulfillmentProcessQuantityInnerPacks'], 'Number');
      }
      if (data.hasOwnProperty('inFulfillmentProcessQuantityPallets')) {
        obj['inFulfillmentProcessQuantityPallets'] = ApiClient.convertToType(data['inFulfillmentProcessQuantityPallets'], 'Number');
      }
      if (data.hasOwnProperty('onHandQuantityCases')) {
        obj['onHandQuantityCases'] = ApiClient.convertToType(data['onHandQuantityCases'], 'Number');
      }
      if (data.hasOwnProperty('onHandQuantityInnerPacks')) {
        obj['onHandQuantityInnerPacks'] = ApiClient.convertToType(data['onHandQuantityInnerPacks'], 'Number');
      }
      if (data.hasOwnProperty('onHandQuantityPallets')) {
        obj['onHandQuantityPallets'] = ApiClient.convertToType(data['onHandQuantityPallets'], 'Number');
      }
      if (data.hasOwnProperty('openOrderQuantityCases')) {
        obj['openOrderQuantityCases'] = ApiClient.convertToType(data['openOrderQuantityCases'], 'Number');
      }
      if (data.hasOwnProperty('openOrderQuantityInnerPacks')) {
        obj['openOrderQuantityInnerPacks'] = ApiClient.convertToType(data['openOrderQuantityInnerPacks'], 'Number');
      }
      if (data.hasOwnProperty('openOrderQuantityPallets')) {
        obj['openOrderQuantityPallets'] = ApiClient.convertToType(data['openOrderQuantityPallets'], 'Number');
      }
      if (data.hasOwnProperty('openPOQuantityCases')) {
        obj['openPOQuantityCases'] = ApiClient.convertToType(data['openPOQuantityCases'], 'Number');
      }
      if (data.hasOwnProperty('openPOQuantityInnerPacks')) {
        obj['openPOQuantityInnerPacks'] = ApiClient.convertToType(data['openPOQuantityInnerPacks'], 'Number');
      }
      if (data.hasOwnProperty('openPOQuantityPallets')) {
        obj['openPOQuantityPallets'] = ApiClient.convertToType(data['openPOQuantityPallets'], 'Number');
      }
      if (data.hasOwnProperty('orderableQuantityCases')) {
        obj['orderableQuantityCases'] = ApiClient.convertToType(data['orderableQuantityCases'], 'Number');
      }
      if (data.hasOwnProperty('orderableQuantityInnerPacks')) {
        obj['orderableQuantityInnerPacks'] = ApiClient.convertToType(data['orderableQuantityInnerPacks'], 'Number');
      }
      if (data.hasOwnProperty('orderableQuantityPallets')) {
        obj['orderableQuantityPallets'] = ApiClient.convertToType(data['orderableQuantityPallets'], 'Number');
      }
      if (data.hasOwnProperty('unallocatableQuantityCases')) {
        obj['unallocatableQuantityCases'] = ApiClient.convertToType(data['unallocatableQuantityCases'], 'Number');
      }
      if (data.hasOwnProperty('unallocatableQuantityInnerPacks')) {
        obj['unallocatableQuantityInnerPacks'] = ApiClient.convertToType(data['unallocatableQuantityInnerPacks'], 'Number');
      }
      if (data.hasOwnProperty('unallocatableQuantityPallets')) {
        obj['unallocatableQuantityPallets'] = ApiClient.convertToType(data['unallocatableQuantityPallets'], 'Number');
      }
      if (data.hasOwnProperty('unavailableQuantityCases')) {
        obj['unavailableQuantityCases'] = ApiClient.convertToType(data['unavailableQuantityCases'], 'Number');
      }
      if (data.hasOwnProperty('unavailableQuantityInnerPacks')) {
        obj['unavailableQuantityInnerPacks'] = ApiClient.convertToType(data['unavailableQuantityInnerPacks'], 'Number');
      }
      if (data.hasOwnProperty('unavailableQuantityPallets')) {
        obj['unavailableQuantityPallets'] = ApiClient.convertToType(data['unavailableQuantityPallets'], 'Number');
      }
      if (data.hasOwnProperty('totalDemand')) {
        obj['totalDemand'] = ApiClient.convertToType(data['totalDemand'], 'Number');
      }
      if (data.hasOwnProperty('nextRequestDeliveryDate')) {
        obj['nextRequestDeliveryDate'] = ApiClient.convertToType(data['nextRequestDeliveryDate'], 'Date');
      }
      if (data.hasOwnProperty('createDate')) {
        obj['createDate'] = ApiClient.convertToType(data['createDate'], 'Date');
      }
      if (data.hasOwnProperty('modifyDate')) {
        obj['modifyDate'] = ApiClient.convertToType(data['modifyDate'], 'Date');
      }
      if (data.hasOwnProperty('customFields')) {
        obj['customFields'] = ApiClient.convertToType(data['customFields'], {'String': Object});
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} sku
   */
  exports.prototype['sku'] = undefined;
  /**
   * @member {Number} lobId
   */
  exports.prototype['lobId'] = undefined;
  /**
   * @member {Number} warehouseId
   */
  exports.prototype['warehouseId'] = undefined;
  /**
   * @member {Number} onHandQuantity
   */
  exports.prototype['onHandQuantity'] = undefined;
  /**
   * @member {Number} unavailableQuantity
   */
  exports.prototype['unavailableQuantity'] = undefined;
  /**
   * @member {Number} openPOQuantity
   */
  exports.prototype['openPOQuantity'] = undefined;
  /**
   * @member {Number} openOrderQuantity
   */
  exports.prototype['openOrderQuantity'] = undefined;
  /**
   * @member {Number} availableQuantity
   */
  exports.prototype['availableQuantity'] = undefined;
  /**
   * @member {Number} damagedQuantity
   */
  exports.prototype['damagedQuantity'] = undefined;
  /**
   * @member {Number} inFulfillmentProcessQuantity
   */
  exports.prototype['inFulfillmentProcessQuantity'] = undefined;
  /**
   * @member {Number} orderableQuantity
   */
  exports.prototype['orderableQuantity'] = undefined;
  /**
   * @member {Number} unallocatableQuantity
   */
  exports.prototype['unallocatableQuantity'] = undefined;
  /**
   * @member {Number} daysOnHand
   */
  exports.prototype['daysOnHand'] = undefined;
  /**
   * @member {String} stockStatus
   */
  exports.prototype['stockStatus'] = undefined;
  /**
   * @member {Number} availableQuantityCases
   */
  exports.prototype['availableQuantityCases'] = undefined;
  /**
   * @member {Number} availableQuantityInnerPacks
   */
  exports.prototype['availableQuantityInnerPacks'] = undefined;
  /**
   * @member {Number} availableQuantityPallets
   */
  exports.prototype['availableQuantityPallets'] = undefined;
  /**
   * @member {Number} damagedQuantityCases
   */
  exports.prototype['damagedQuantityCases'] = undefined;
  /**
   * @member {Number} damagedQuantityInnerPacks
   */
  exports.prototype['damagedQuantityInnerPacks'] = undefined;
  /**
   * @member {Number} damagedQuantityPallets
   */
  exports.prototype['damagedQuantityPallets'] = undefined;
  /**
   * @member {Number} inFulfillmentProcessQuantityCases
   */
  exports.prototype['inFulfillmentProcessQuantityCases'] = undefined;
  /**
   * @member {Number} inFulfillmentProcessQuantityInnerPacks
   */
  exports.prototype['inFulfillmentProcessQuantityInnerPacks'] = undefined;
  /**
   * @member {Number} inFulfillmentProcessQuantityPallets
   */
  exports.prototype['inFulfillmentProcessQuantityPallets'] = undefined;
  /**
   * @member {Number} onHandQuantityCases
   */
  exports.prototype['onHandQuantityCases'] = undefined;
  /**
   * @member {Number} onHandQuantityInnerPacks
   */
  exports.prototype['onHandQuantityInnerPacks'] = undefined;
  /**
   * @member {Number} onHandQuantityPallets
   */
  exports.prototype['onHandQuantityPallets'] = undefined;
  /**
   * @member {Number} openOrderQuantityCases
   */
  exports.prototype['openOrderQuantityCases'] = undefined;
  /**
   * @member {Number} openOrderQuantityInnerPacks
   */
  exports.prototype['openOrderQuantityInnerPacks'] = undefined;
  /**
   * @member {Number} openOrderQuantityPallets
   */
  exports.prototype['openOrderQuantityPallets'] = undefined;
  /**
   * @member {Number} openPOQuantityCases
   */
  exports.prototype['openPOQuantityCases'] = undefined;
  /**
   * @member {Number} openPOQuantityInnerPacks
   */
  exports.prototype['openPOQuantityInnerPacks'] = undefined;
  /**
   * @member {Number} openPOQuantityPallets
   */
  exports.prototype['openPOQuantityPallets'] = undefined;
  /**
   * @member {Number} orderableQuantityCases
   */
  exports.prototype['orderableQuantityCases'] = undefined;
  /**
   * @member {Number} orderableQuantityInnerPacks
   */
  exports.prototype['orderableQuantityInnerPacks'] = undefined;
  /**
   * @member {Number} orderableQuantityPallets
   */
  exports.prototype['orderableQuantityPallets'] = undefined;
  /**
   * @member {Number} unallocatableQuantityCases
   */
  exports.prototype['unallocatableQuantityCases'] = undefined;
  /**
   * @member {Number} unallocatableQuantityInnerPacks
   */
  exports.prototype['unallocatableQuantityInnerPacks'] = undefined;
  /**
   * @member {Number} unallocatableQuantityPallets
   */
  exports.prototype['unallocatableQuantityPallets'] = undefined;
  /**
   * @member {Number} unavailableQuantityCases
   */
  exports.prototype['unavailableQuantityCases'] = undefined;
  /**
   * @member {Number} unavailableQuantityInnerPacks
   */
  exports.prototype['unavailableQuantityInnerPacks'] = undefined;
  /**
   * @member {Number} unavailableQuantityPallets
   */
  exports.prototype['unavailableQuantityPallets'] = undefined;
  /**
   * @member {Number} totalDemand
   */
  exports.prototype['totalDemand'] = undefined;
  /**
   * @member {Date} nextRequestDeliveryDate
   */
  exports.prototype['nextRequestDeliveryDate'] = undefined;
  /**
   * @member {Date} createDate
   */
  exports.prototype['createDate'] = undefined;
  /**
   * @member {Date} modifyDate
   */
  exports.prototype['modifyDate'] = undefined;
  /**
   * @member {Object.<String, Object>} customFields
   */
  exports.prototype['customFields'] = undefined;



  return exports;
}));


