/**
 * Infoplus API
 * Infoplus API.
 *
 * OpenAPI spec version: beta
 * Contact: api@infopluscommerce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/FulfillmentProcessPickBatchGroup'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/FulfillmentProcessPickBatchGroup'));
  } else {
    // Browser globals (root is window)
    if (!root.infoplus) {
      root.infoplus = {};
    }
    root.infoplus.FulfillmentProcessPickBatchGroupApi = factory(root.infoplus.ApiClient, root.infoplus.FulfillmentProcessPickBatchGroup);
  }
}(this, function(ApiClient, FulfillmentProcessPickBatchGroup) {
  'use strict';

  /**
   * FulfillmentProcessPickBatchGroup service.
   * @module api/FulfillmentProcessPickBatchGroupApi
   * @version beta
   */

  /**
   * Constructs a new FulfillmentProcessPickBatchGroupApi. 
   * @alias module:api/FulfillmentProcessPickBatchGroupApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getFulfillmentProcessGroupPicksByById operation.
     * @callback module:api/FulfillmentProcessPickBatchGroupApi~getFulfillmentProcessGroupPicksByByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/FulfillmentProcessPickBatchGroup} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a fulfillmentProcessPickBatchGroup by id
     * Returns the fulfillmentProcessPickBatchGroup identified by the specified id.
     * @param {String} fulfillmentProcessPickBatchGroupId Id of fulfillmentProcessPickBatchGroup to be returned.
     * @param {module:api/FulfillmentProcessPickBatchGroupApi~getFulfillmentProcessGroupPicksByByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/FulfillmentProcessPickBatchGroup}
     */
    this.getFulfillmentProcessGroupPicksByById = function(fulfillmentProcessPickBatchGroupId, callback) {
      var postBody = null;

      // verify the required parameter 'fulfillmentProcessPickBatchGroupId' is set
      if (fulfillmentProcessPickBatchGroupId === undefined || fulfillmentProcessPickBatchGroupId === null) {
        throw new Error("Missing the required parameter 'fulfillmentProcessPickBatchGroupId' when calling getFulfillmentProcessGroupPicksByById");
      }


      var pathParams = {
        'fulfillmentProcessPickBatchGroupId': fulfillmentProcessPickBatchGroupId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = FulfillmentProcessPickBatchGroup;

      return this.apiClient.callApi(
        '/beta/fulfillmentProcessPickBatchGroup/{fulfillmentProcessPickBatchGroupId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getFulfillmentProcessPickBatchGroupBySearchText operation.
     * @callback module:api/FulfillmentProcessPickBatchGroupApi~getFulfillmentProcessPickBatchGroupBySearchTextCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/FulfillmentProcessPickBatchGroup>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Search fulfillmentProcessPickBatchGroups
     * Returns the list of fulfillmentProcessPickBatchGroups that match the given searchText.
     * @param {Object} opts Optional parameters
     * @param {String} opts.searchText Search text, used to filter results.
     * @param {Number} opts.page Result page number.  Defaults to 1.
     * @param {Number} opts.limit Maximum results per page.  Defaults to 20.  Max allowed value is 250.
     * @param {module:api/FulfillmentProcessPickBatchGroupApi~getFulfillmentProcessPickBatchGroupBySearchTextCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/FulfillmentProcessPickBatchGroup>}
     */
    this.getFulfillmentProcessPickBatchGroupBySearchText = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'searchText': opts['searchText'],
        'page': opts['page'],
        'limit': opts['limit'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [FulfillmentProcessPickBatchGroup];

      return this.apiClient.callApi(
        '/beta/fulfillmentProcessPickBatchGroup/search', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
