/**
 * Infoplus API
 * Infoplus API.
 *
 * OpenAPI spec version: v3.0
 * Contact: api@infopluscommerce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ApiResponse', 'model/ReceivingWorksheet', 'model/RecordFile'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ApiResponse'), require('../model/ReceivingWorksheet'), require('../model/RecordFile'));
  } else {
    // Browser globals (root is window)
    if (!root.infoplus) {
      root.infoplus = {};
    }
    root.infoplus.ReceivingWorksheetApi = factory(root.infoplus.ApiClient, root.infoplus.ApiResponse, root.infoplus.ReceivingWorksheet, root.infoplus.RecordFile);
  }
}(this, function(ApiClient, ApiResponse, ReceivingWorksheet, RecordFile) {
  'use strict';

  /**
   * ReceivingWorksheet service.
   * @module api/ReceivingWorksheetApi
   * @version v3.0
   */

  /**
   * Constructs a new ReceivingWorksheetApi. 
   * @alias module:api/ReceivingWorksheetApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the addReceivingWorksheet operation.
     * @callback module:api/ReceivingWorksheetApi~addReceivingWorksheetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ReceivingWorksheet} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a receivingWorksheet
     * Inserts a new receivingWorksheet using the specified data.
     * @param {module:model/ReceivingWorksheet} body ReceivingWorksheet to be inserted.
     * @param {module:api/ReceivingWorksheetApi~addReceivingWorksheetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ReceivingWorksheet}
     */
    this.addReceivingWorksheet = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling addReceivingWorksheet");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ReceivingWorksheet;

      return this.apiClient.callApi(
        '/v3.0/receivingWorksheet', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the addReceivingWorksheetAudit operation.
     * @callback module:api/ReceivingWorksheetApi~addReceivingWorksheetAuditCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add new audit for a receivingWorksheet
     * Adds an audit to an existing receivingWorksheet.
     * @param {Number} receivingWorksheetId Id of the receivingWorksheet to add an audit to
     * @param {String} receivingWorksheetAudit The audit to add
     * @param {module:api/ReceivingWorksheetApi~addReceivingWorksheetAuditCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.addReceivingWorksheetAudit = function(receivingWorksheetId, receivingWorksheetAudit, callback) {
      var postBody = null;

      // verify the required parameter 'receivingWorksheetId' is set
      if (receivingWorksheetId === undefined || receivingWorksheetId === null) {
        throw new Error("Missing the required parameter 'receivingWorksheetId' when calling addReceivingWorksheetAudit");
      }

      // verify the required parameter 'receivingWorksheetAudit' is set
      if (receivingWorksheetAudit === undefined || receivingWorksheetAudit === null) {
        throw new Error("Missing the required parameter 'receivingWorksheetAudit' when calling addReceivingWorksheetAudit");
      }


      var pathParams = {
        'receivingWorksheetId': receivingWorksheetId,
        'receivingWorksheetAudit': receivingWorksheetAudit
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/v3.0/receivingWorksheet/{receivingWorksheetId}/audit/{receivingWorksheetAudit}', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the addReceivingWorksheetFile operation.
     * @callback module:api/ReceivingWorksheetApi~addReceivingWorksheetFileCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Attach a file to a receivingWorksheet
     * Adds a file to an existing receivingWorksheet.
     * @param {Number} receivingWorksheetId Id of the receivingWorksheet to add a file to
     * @param {String} fileName Name of file
     * @param {module:api/ReceivingWorksheetApi~addReceivingWorksheetFileCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.addReceivingWorksheetFile = function(receivingWorksheetId, fileName, callback) {
      var postBody = null;

      // verify the required parameter 'receivingWorksheetId' is set
      if (receivingWorksheetId === undefined || receivingWorksheetId === null) {
        throw new Error("Missing the required parameter 'receivingWorksheetId' when calling addReceivingWorksheetFile");
      }

      // verify the required parameter 'fileName' is set
      if (fileName === undefined || fileName === null) {
        throw new Error("Missing the required parameter 'fileName' when calling addReceivingWorksheetFile");
      }


      var pathParams = {
        'receivingWorksheetId': receivingWorksheetId,
        'fileName': fileName
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/v3.0/receivingWorksheet/{receivingWorksheetId}/file/{fileName}', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the addReceivingWorksheetFileByURL operation.
     * @callback module:api/ReceivingWorksheetApi~addReceivingWorksheetFileByURLCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Attach a file to a receivingWorksheet by URL.
     * Adds a file to an existing receivingWorksheet by URL.
     * @param {module:model/RecordFile} body The url and optionly fileName to be used.
     * @param {Number} receivingWorksheetId Id of the receivingWorksheet to add an file to
     * @param {module:api/ReceivingWorksheetApi~addReceivingWorksheetFileByURLCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.addReceivingWorksheetFileByURL = function(body, receivingWorksheetId, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling addReceivingWorksheetFileByURL");
      }

      // verify the required parameter 'receivingWorksheetId' is set
      if (receivingWorksheetId === undefined || receivingWorksheetId === null) {
        throw new Error("Missing the required parameter 'receivingWorksheetId' when calling addReceivingWorksheetFileByURL");
      }


      var pathParams = {
        'receivingWorksheetId': receivingWorksheetId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/v3.0/receivingWorksheet/{receivingWorksheetId}/file', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the addReceivingWorksheetTag operation.
     * @callback module:api/ReceivingWorksheetApi~addReceivingWorksheetTagCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add new tags for a receivingWorksheet.
     * Adds a tag to an existing receivingWorksheet.
     * @param {Number} receivingWorksheetId Id of the receivingWorksheet to add a tag to
     * @param {String} receivingWorksheetTag The tag to add
     * @param {module:api/ReceivingWorksheetApi~addReceivingWorksheetTagCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.addReceivingWorksheetTag = function(receivingWorksheetId, receivingWorksheetTag, callback) {
      var postBody = null;

      // verify the required parameter 'receivingWorksheetId' is set
      if (receivingWorksheetId === undefined || receivingWorksheetId === null) {
        throw new Error("Missing the required parameter 'receivingWorksheetId' when calling addReceivingWorksheetTag");
      }

      // verify the required parameter 'receivingWorksheetTag' is set
      if (receivingWorksheetTag === undefined || receivingWorksheetTag === null) {
        throw new Error("Missing the required parameter 'receivingWorksheetTag' when calling addReceivingWorksheetTag");
      }


      var pathParams = {
        'receivingWorksheetId': receivingWorksheetId,
        'receivingWorksheetTag': receivingWorksheetTag
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/v3.0/receivingWorksheet/{receivingWorksheetId}/tag/{receivingWorksheetTag}', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteReceivingWorksheet operation.
     * @callback module:api/ReceivingWorksheetApi~deleteReceivingWorksheetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a receivingWorksheet
     * Deletes the receivingWorksheet identified by the specified id.
     * @param {Number} receivingWorksheetId Id of the receivingWorksheet to be deleted.
     * @param {module:api/ReceivingWorksheetApi~deleteReceivingWorksheetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.deleteReceivingWorksheet = function(receivingWorksheetId, callback) {
      var postBody = null;

      // verify the required parameter 'receivingWorksheetId' is set
      if (receivingWorksheetId === undefined || receivingWorksheetId === null) {
        throw new Error("Missing the required parameter 'receivingWorksheetId' when calling deleteReceivingWorksheet");
      }


      var pathParams = {
        'receivingWorksheetId': receivingWorksheetId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/v3.0/receivingWorksheet/{receivingWorksheetId}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteReceivingWorksheetFile operation.
     * @callback module:api/ReceivingWorksheetApi~deleteReceivingWorksheetFileCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a file for a receivingWorksheet.
     * Deletes an existing receivingWorksheet file using the specified data.
     * @param {Number} receivingWorksheetId Id of the receivingWorksheet to remove file from
     * @param {Number} fileId Id of the file to delete
     * @param {module:api/ReceivingWorksheetApi~deleteReceivingWorksheetFileCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.deleteReceivingWorksheetFile = function(receivingWorksheetId, fileId, callback) {
      var postBody = null;

      // verify the required parameter 'receivingWorksheetId' is set
      if (receivingWorksheetId === undefined || receivingWorksheetId === null) {
        throw new Error("Missing the required parameter 'receivingWorksheetId' when calling deleteReceivingWorksheetFile");
      }

      // verify the required parameter 'fileId' is set
      if (fileId === undefined || fileId === null) {
        throw new Error("Missing the required parameter 'fileId' when calling deleteReceivingWorksheetFile");
      }


      var pathParams = {
        'receivingWorksheetId': receivingWorksheetId,
        'fileId': fileId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/v3.0/receivingWorksheet/{receivingWorksheetId}/file/{fileId}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteReceivingWorksheetTag operation.
     * @callback module:api/ReceivingWorksheetApi~deleteReceivingWorksheetTagCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a tag for a receivingWorksheet.
     * Deletes an existing receivingWorksheet tag using the specified data.
     * @param {Number} receivingWorksheetId Id of the receivingWorksheet to remove tag from
     * @param {String} receivingWorksheetTag The tag to delete
     * @param {module:api/ReceivingWorksheetApi~deleteReceivingWorksheetTagCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.deleteReceivingWorksheetTag = function(receivingWorksheetId, receivingWorksheetTag, callback) {
      var postBody = null;

      // verify the required parameter 'receivingWorksheetId' is set
      if (receivingWorksheetId === undefined || receivingWorksheetId === null) {
        throw new Error("Missing the required parameter 'receivingWorksheetId' when calling deleteReceivingWorksheetTag");
      }

      // verify the required parameter 'receivingWorksheetTag' is set
      if (receivingWorksheetTag === undefined || receivingWorksheetTag === null) {
        throw new Error("Missing the required parameter 'receivingWorksheetTag' when calling deleteReceivingWorksheetTag");
      }


      var pathParams = {
        'receivingWorksheetId': receivingWorksheetId,
        'receivingWorksheetTag': receivingWorksheetTag
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/v3.0/receivingWorksheet/{receivingWorksheetId}/tag/{receivingWorksheetTag}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getDuplicateReceivingWorksheetById operation.
     * @callback module:api/ReceivingWorksheetApi~getDuplicateReceivingWorksheetByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ReceivingWorksheet} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a duplicated a receivingWorksheet by id
     * Returns a duplicated receivingWorksheet identified by the specified id.
     * @param {Number} receivingWorksheetId Id of the receivingWorksheet to be duplicated.
     * @param {module:api/ReceivingWorksheetApi~getDuplicateReceivingWorksheetByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ReceivingWorksheet}
     */
    this.getDuplicateReceivingWorksheetById = function(receivingWorksheetId, callback) {
      var postBody = null;

      // verify the required parameter 'receivingWorksheetId' is set
      if (receivingWorksheetId === undefined || receivingWorksheetId === null) {
        throw new Error("Missing the required parameter 'receivingWorksheetId' when calling getDuplicateReceivingWorksheetById");
      }


      var pathParams = {
        'receivingWorksheetId': receivingWorksheetId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = ReceivingWorksheet;

      return this.apiClient.callApi(
        '/v3.0/receivingWorksheet/duplicate/{receivingWorksheetId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getReceivingWorksheetByFilter operation.
     * @callback module:api/ReceivingWorksheetApi~getReceivingWorksheetByFilterCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/ReceivingWorksheet>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Search receivingWorksheets by filter
     * Returns the list of receivingWorksheets that match the given filter.
     * @param {Object} opts Optional parameters
     * @param {String} opts.filter Query string, used to filter results.
     * @param {Number} opts.page Result page number.  Defaults to 1.
     * @param {Number} opts.limit Maximum results per page.  Defaults to 20.  Max allowed value is 250.
     * @param {String} opts.sort Sort results by specified field.
     * @param {module:api/ReceivingWorksheetApi~getReceivingWorksheetByFilterCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/ReceivingWorksheet>}
     */
    this.getReceivingWorksheetByFilter = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'filter': opts['filter'],
        'page': opts['page'],
        'limit': opts['limit'],
        'sort': opts['sort'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [ReceivingWorksheet];

      return this.apiClient.callApi(
        '/v3.0/receivingWorksheet/search', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getReceivingWorksheetById operation.
     * @callback module:api/ReceivingWorksheetApi~getReceivingWorksheetByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ReceivingWorksheet} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a receivingWorksheet by id
     * Returns the receivingWorksheet identified by the specified id.
     * @param {Number} receivingWorksheetId Id of the receivingWorksheet to be returned.
     * @param {module:api/ReceivingWorksheetApi~getReceivingWorksheetByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ReceivingWorksheet}
     */
    this.getReceivingWorksheetById = function(receivingWorksheetId, callback) {
      var postBody = null;

      // verify the required parameter 'receivingWorksheetId' is set
      if (receivingWorksheetId === undefined || receivingWorksheetId === null) {
        throw new Error("Missing the required parameter 'receivingWorksheetId' when calling getReceivingWorksheetById");
      }


      var pathParams = {
        'receivingWorksheetId': receivingWorksheetId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = ReceivingWorksheet;

      return this.apiClient.callApi(
        '/v3.0/receivingWorksheet/{receivingWorksheetId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getReceivingWorksheetFiles operation.
     * @callback module:api/ReceivingWorksheetApi~getReceivingWorksheetFilesCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get the files for a receivingWorksheet.
     * Get all existing receivingWorksheet files.
     * @param {Number} receivingWorksheetId Id of the receivingWorksheet to get files for
     * @param {module:api/ReceivingWorksheetApi~getReceivingWorksheetFilesCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.getReceivingWorksheetFiles = function(receivingWorksheetId, callback) {
      var postBody = null;

      // verify the required parameter 'receivingWorksheetId' is set
      if (receivingWorksheetId === undefined || receivingWorksheetId === null) {
        throw new Error("Missing the required parameter 'receivingWorksheetId' when calling getReceivingWorksheetFiles");
      }


      var pathParams = {
        'receivingWorksheetId': receivingWorksheetId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/v3.0/receivingWorksheet/{receivingWorksheetId}/file', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getReceivingWorksheetTags operation.
     * @callback module:api/ReceivingWorksheetApi~getReceivingWorksheetTagsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get the tags for a receivingWorksheet.
     * Get all existing receivingWorksheet tags.
     * @param {Number} receivingWorksheetId Id of the receivingWorksheet to get tags for
     * @param {module:api/ReceivingWorksheetApi~getReceivingWorksheetTagsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.getReceivingWorksheetTags = function(receivingWorksheetId, callback) {
      var postBody = null;

      // verify the required parameter 'receivingWorksheetId' is set
      if (receivingWorksheetId === undefined || receivingWorksheetId === null) {
        throw new Error("Missing the required parameter 'receivingWorksheetId' when calling getReceivingWorksheetTags");
      }


      var pathParams = {
        'receivingWorksheetId': receivingWorksheetId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/v3.0/receivingWorksheet/{receivingWorksheetId}/tag', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateReceivingWorksheet operation.
     * @callback module:api/ReceivingWorksheetApi~updateReceivingWorksheetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update a receivingWorksheet
     * Updates an existing receivingWorksheet using the specified data.
     * @param {module:model/ReceivingWorksheet} body ReceivingWorksheet to be updated.
     * @param {module:api/ReceivingWorksheetApi~updateReceivingWorksheetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.updateReceivingWorksheet = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updateReceivingWorksheet");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/v3.0/receivingWorksheet', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateReceivingWorksheetCustomFields operation.
     * @callback module:api/ReceivingWorksheetApi~updateReceivingWorksheetCustomFieldsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update a receivingWorksheet custom fields
     * Updates an existing receivingWorksheet custom fields using the specified data.
     * @param {module:model/ReceivingWorksheet} body ReceivingWorksheet to be updated.
     * @param {module:api/ReceivingWorksheetApi~updateReceivingWorksheetCustomFieldsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.updateReceivingWorksheetCustomFields = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updateReceivingWorksheetCustomFields");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/v3.0/receivingWorksheet/customFields', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
