/**
 * Infoplus API
 * Infoplus API.
 *
 * OpenAPI spec version: v3.0
 * Contact: api@infopluscommerce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.infoplus);
  }
}(this, function(expect, infoplus) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new infoplus.LowStock();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LowStock', function() {
    it('should create an instance of LowStock', function() {
      // uncomment below and update the code to test LowStock
      //var instane = new infoplus.LowStock();
      //expect(instance).to.be.a(infoplus.LowStock);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new infoplus.LowStock();
      //expect(instance).to.be();
    });

    it('should have the property warehouseId (base name: "warehouseId")', function() {
      // uncomment below and update the code to test the property warehouseId
      //var instane = new infoplus.LowStock();
      //expect(instance).to.be();
    });

    it('should have the property lowLevelDate (base name: "lowLevelDate")', function() {
      // uncomment below and update the code to test the property lowLevelDate
      //var instane = new infoplus.LowStock();
      //expect(instance).to.be();
    });

    it('should have the property lowStockMessage (base name: "lowStockMessage")', function() {
      // uncomment below and update the code to test the property lowStockMessage
      //var instane = new infoplus.LowStock();
      //expect(instance).to.be();
    });

    it('should have the property printFlag (base name: "printFlag")', function() {
      // uncomment below and update the code to test the property printFlag
      //var instane = new infoplus.LowStock();
      //expect(instance).to.be();
    });

    it('should have the property isDelayed (base name: "isDelayed")', function() {
      // uncomment below and update the code to test the property isDelayed
      //var instane = new infoplus.LowStock();
      //expect(instance).to.be();
    });

    it('should have the property createDate (base name: "createDate")', function() {
      // uncomment below and update the code to test the property createDate
      //var instane = new infoplus.LowStock();
      //expect(instance).to.be();
    });

    it('should have the property modifyDate (base name: "modifyDate")', function() {
      // uncomment below and update the code to test the property modifyDate
      //var instane = new infoplus.LowStock();
      //expect(instance).to.be();
    });

    it('should have the property customFields (base name: "customFields")', function() {
      // uncomment below and update the code to test the property customFields
      //var instane = new infoplus.LowStock();
      //expect(instance).to.be();
    });

    it('should have the property sku (base name: "sku")', function() {
      // uncomment below and update the code to test the property sku
      //var instane = new infoplus.LowStock();
      //expect(instance).to.be();
    });

  });

}));
