/**
 * Infoplus API
 * Infoplus API.
 *
 * OpenAPI spec version: beta
 * Contact: api@infopluscommerce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.infoplus);
  }
}(this, function(expect, infoplus) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new infoplus.OrderLineActivity();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OrderLineActivity', function() {
    it('should create an instance of OrderLineActivity', function() {
      // uncomment below and update the code to test OrderLineActivity
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be.a(infoplus.OrderLineActivity);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property createDate (base name: "createDate")', function() {
      // uncomment below and update the code to test the property createDate
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property modifyDate (base name: "modifyDate")', function() {
      // uncomment below and update the code to test the property modifyDate
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property orderNo (base name: "orderNo")', function() {
      // uncomment below and update the code to test the property orderNo
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property lobId (base name: "lobId")', function() {
      // uncomment below and update the code to test the property lobId
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property sku (base name: "sku")', function() {
      // uncomment below and update the code to test the property sku
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property poNoId (base name: "poNoId")', function() {
      // uncomment below and update the code to test the property poNoId
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property lineItemId (base name: "lineItemId")', function() {
      // uncomment below and update the code to test the property lineItemId
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property orderCreateDate (base name: "orderCreateDate")', function() {
      // uncomment below and update the code to test the property orderCreateDate
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property orderModifyDate (base name: "orderModifyDate")', function() {
      // uncomment below and update the code to test the property orderModifyDate
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property crossDock (base name: "crossDock")', function() {
      // uncomment below and update the code to test the property crossDock
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property processNoId (base name: "processNoId")', function() {
      // uncomment below and update the code to test the property processNoId
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property orderedQty (base name: "orderedQty")', function() {
      // uncomment below and update the code to test the property orderedQty
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property allowedQty (base name: "allowedQty")', function() {
      // uncomment below and update the code to test the property allowedQty
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property shippedQty (base name: "shippedQty")', function() {
      // uncomment below and update the code to test the property shippedQty
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property backorderQty (base name: "backorderQty")', function() {
      // uncomment below and update the code to test the property backorderQty
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property adjustCode (base name: "adjustCode")', function() {
      // uncomment below and update the code to test the property adjustCode
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property processFlag (base name: "processFlag")', function() {
      // uncomment below and update the code to test the property processFlag
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property revDate (base name: "revDate")', function() {
      // uncomment below and update the code to test the property revDate
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property restrictionRule (base name: "restrictionRule")', function() {
      // uncomment below and update the code to test the property restrictionRule
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property unitCost (base name: "unitCost")', function() {
      // uncomment below and update the code to test the property unitCost
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property unitSell (base name: "unitSell")', function() {
      // uncomment below and update the code to test the property unitSell
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property unitDiscount (base name: "unitDiscount")', function() {
      // uncomment below and update the code to test the property unitDiscount
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property extendedCost (base name: "extendedCost")', function() {
      // uncomment below and update the code to test the property extendedCost
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property extendedSell (base name: "extendedSell")', function() {
      // uncomment below and update the code to test the property extendedSell
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property extendedDiscount (base name: "extendedDiscount")', function() {
      // uncomment below and update the code to test the property extendedDiscount
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property ncExtendedSell (base name: "ncExtendedSell")', function() {
      // uncomment below and update the code to test the property ncExtendedSell
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property per (base name: "per")', function() {
      // uncomment below and update the code to test the property per
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property chargeCode (base name: "chargeCode")', function() {
      // uncomment below and update the code to test the property chargeCode
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property distributionCode (base name: "distributionCode")', function() {
      // uncomment below and update the code to test the property distributionCode
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property upc (base name: "upc")', function() {
      // uncomment below and update the code to test the property upc
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property vendorSKU (base name: "vendorSKU")', function() {
      // uncomment below and update the code to test the property vendorSKU
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property orderSourceSKU (base name: "orderSourceSKU")', function() {
      // uncomment below and update the code to test the property orderSourceSKU
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property itemMajorGroupId (base name: "itemMajorGroupId")', function() {
      // uncomment below and update the code to test the property itemMajorGroupId
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property masterMajorGroupName (base name: "masterMajorGroupName")', function() {
      // uncomment below and update the code to test the property masterMajorGroupName
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property itemSubGroupId (base name: "itemSubGroupId")', function() {
      // uncomment below and update the code to test the property itemSubGroupId
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property masterSubGroupName (base name: "masterSubGroupName")', function() {
      // uncomment below and update the code to test the property masterSubGroupName
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property itemProductCodeId (base name: "itemProductCodeId")', function() {
      // uncomment below and update the code to test the property itemProductCodeId
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property masterProductionCodeName (base name: "masterProductionCodeName")', function() {
      // uncomment below and update the code to test the property masterProductionCodeName
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property itemAccountCodeId (base name: "itemAccountCodeId")', function() {
      // uncomment below and update the code to test the property itemAccountCodeId
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property masterAccountCodeName (base name: "masterAccountCodeName")', function() {
      // uncomment below and update the code to test the property masterAccountCodeName
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property itemSummaryCodeId (base name: "itemSummaryCodeId")', function() {
      // uncomment below and update the code to test the property itemSummaryCodeId
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property masterSummaryCodeName (base name: "masterSummaryCodeName")', function() {
      // uncomment below and update the code to test the property masterSummaryCodeName
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property itemLegacyLowStockContactId (base name: "itemLegacyLowStockContactId")', function() {
      // uncomment below and update the code to test the property itemLegacyLowStockContactId
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property lowStockContactName (base name: "lowStockContactName")', function() {
      // uncomment below and update the code to test the property lowStockContactName
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property sector (base name: "sector")', function() {
      // uncomment below and update the code to test the property sector
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property weightPerWrap (base name: "weightPerWrap")', function() {
      // uncomment below and update the code to test the property weightPerWrap
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property itemWeight (base name: "itemWeight")', function() {
      // uncomment below and update the code to test the property itemWeight
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property productionLot (base name: "productionLot")', function() {
      // uncomment below and update the code to test the property productionLot
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property numberOfWraps (base name: "numberOfWraps")', function() {
      // uncomment below and update the code to test the property numberOfWraps
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property numberOfCases (base name: "numberOfCases")', function() {
      // uncomment below and update the code to test the property numberOfCases
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property numberOfTouches (base name: "numberOfTouches")', function() {
      // uncomment below and update the code to test the property numberOfTouches
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property alcoholTypeId (base name: "alcoholTypeId")', function() {
      // uncomment below and update the code to test the property alcoholTypeId
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property alcoholTypeName (base name: "alcoholTypeName")', function() {
      // uncomment below and update the code to test the property alcoholTypeName
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property alcoholContent (base name: "alcoholContent")', function() {
      // uncomment below and update the code to test the property alcoholContent
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property alcoholContainerId (base name: "alcoholContainerId")', function() {
      // uncomment below and update the code to test the property alcoholContainerId
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property alcoholContainerName (base name: "alcoholContainerName")', function() {
      // uncomment below and update the code to test the property alcoholContainerName
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property alcoholContainerVolume (base name: "alcoholContainerVolume")', function() {
      // uncomment below and update the code to test the property alcoholContainerVolume
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property alcoholVintageYear (base name: "alcoholVintageYear")', function() {
      // uncomment below and update the code to test the property alcoholVintageYear
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property alcoholCountryId (base name: "alcoholCountryId")', function() {
      // uncomment below and update the code to test the property alcoholCountryId
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property alcoholCountryName (base name: "alcoholCountryName")', function() {
      // uncomment below and update the code to test the property alcoholCountryName
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property alcoholState (base name: "alcoholState")', function() {
      // uncomment below and update the code to test the property alcoholState
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property alcoholRegion (base name: "alcoholRegion")', function() {
      // uncomment below and update the code to test the property alcoholRegion
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property alcoholBrand (base name: "alcoholBrand")', function() {
      // uncomment below and update the code to test the property alcoholBrand
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property alcoholUPCCode (base name: "alcoholUPCCode")', function() {
      // uncomment below and update the code to test the property alcoholUPCCode
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property alcoholNABCACode (base name: "alcoholNABCACode")', function() {
      // uncomment below and update the code to test the property alcoholNABCACode
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property alcoholUNIMERCCode (base name: "alcoholUNIMERCCode")', function() {
      // uncomment below and update the code to test the property alcoholUNIMERCCode
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property alcoholSCCCode (base name: "alcoholSCCCode")', function() {
      // uncomment below and update the code to test the property alcoholSCCCode
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property alternateUsage (base name: "alternateUsage")', function() {
      // uncomment below and update the code to test the property alternateUsage
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property groupOrderId (base name: "groupOrderId")', function() {
      // uncomment below and update the code to test the property groupOrderId
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property orderStatus (base name: "orderStatus")', function() {
      // uncomment below and update the code to test the property orderStatus
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property orderStatusName (base name: "orderStatusName")', function() {
      // uncomment below and update the code to test the property orderStatusName
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property carrierId (base name: "carrierId")', function() {
      // uncomment below and update the code to test the property carrierId
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property carrierName (base name: "carrierName")', function() {
      // uncomment below and update the code to test the property carrierName
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property mediaCode (base name: "mediaCode")', function() {
      // uncomment below and update the code to test the property mediaCode
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property legacyRestrictionType (base name: "legacyRestrictionType")', function() {
      // uncomment below and update the code to test the property legacyRestrictionType
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property reqTypeName (base name: "reqTypeName")', function() {
      // uncomment below and update the code to test the property reqTypeName
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property legacyServiceType (base name: "legacyServiceType")', function() {
      // uncomment below and update the code to test the property legacyServiceType
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property legacyServiceTypeName (base name: "legacyServiceTypeName")', function() {
      // uncomment below and update the code to test the property legacyServiceTypeName
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property alcoholOrderType (base name: "alcoholOrderType")', function() {
      // uncomment below and update the code to test the property alcoholOrderType
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property distributionChannel (base name: "distributionChannel")', function() {
      // uncomment below and update the code to test the property distributionChannel
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property distributionChannelName (base name: "distributionChannelName")', function() {
      // uncomment below and update the code to test the property distributionChannelName
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property priorityCode (base name: "priorityCode")', function() {
      // uncomment below and update the code to test the property priorityCode
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property orderDate (base name: "orderDate")', function() {
      // uncomment below and update the code to test the property orderDate
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property enteredBy (base name: "enteredBy")', function() {
      // uncomment below and update the code to test the property enteredBy
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property orderReason (base name: "orderReason")', function() {
      // uncomment below and update the code to test the property orderReason
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property customerOrderNo (base name: "customerOrderNo")', function() {
      // uncomment below and update the code to test the property customerOrderNo
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property priceLevel (base name: "priceLevel")', function() {
      // uncomment below and update the code to test the property priceLevel
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property shipBy (base name: "shipBy")', function() {
      // uncomment below and update the code to test the property shipBy
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property stopBackOrders (base name: "stopBackOrders")', function() {
      // uncomment below and update the code to test the property stopBackOrders
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property orderSourceId (base name: "orderSourceId")', function() {
      // uncomment below and update the code to test the property orderSourceId
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property orderSourceName (base name: "orderSourceName")', function() {
      // uncomment below and update the code to test the property orderSourceName
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property integrationPartnerId (base name: "integrationPartnerId")', function() {
      // uncomment below and update the code to test the property integrationPartnerId
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property integrationPartnerName (base name: "integrationPartnerName")', function() {
      // uncomment below and update the code to test the property integrationPartnerName
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property orderLoadProgramId (base name: "orderLoadProgramId")', function() {
      // uncomment below and update the code to test the property orderLoadProgramId
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property orderLoadProgramName (base name: "orderLoadProgramName")', function() {
      // uncomment below and update the code to test the property orderLoadProgramName
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property omsOrderNo (base name: "omsOrderNo")', function() {
      // uncomment below and update the code to test the property omsOrderNo
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property omsCustomerId (base name: "omsCustomerId")', function() {
      // uncomment below and update the code to test the property omsCustomerId
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property shipToAttention (base name: "shipToAttention")', function() {
      // uncomment below and update the code to test the property shipToAttention
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property shipToCompany (base name: "shipToCompany")', function() {
      // uncomment below and update the code to test the property shipToCompany
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property shipToStreet (base name: "shipToStreet")', function() {
      // uncomment below and update the code to test the property shipToStreet
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property shipToStreet2 (base name: "shipToStreet2")', function() {
      // uncomment below and update the code to test the property shipToStreet2
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property shipToStreet3 (base name: "shipToStreet3")', function() {
      // uncomment below and update the code to test the property shipToStreet3
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property shipToCity (base name: "shipToCity")', function() {
      // uncomment below and update the code to test the property shipToCity
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property shipToState (base name: "shipToState")', function() {
      // uncomment below and update the code to test the property shipToState
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property shipToZip (base name: "shipToZip")', function() {
      // uncomment below and update the code to test the property shipToZip
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property shipToCountry (base name: "shipToCountry")', function() {
      // uncomment below and update the code to test the property shipToCountry
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property shipToPhone (base name: "shipToPhone")', function() {
      // uncomment below and update the code to test the property shipToPhone
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property shipToEmail (base name: "shipToEmail")', function() {
      // uncomment below and update the code to test the property shipToEmail
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property billToAttention (base name: "billToAttention")', function() {
      // uncomment below and update the code to test the property billToAttention
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property billToCompany (base name: "billToCompany")', function() {
      // uncomment below and update the code to test the property billToCompany
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property billToStreet (base name: "billToStreet")', function() {
      // uncomment below and update the code to test the property billToStreet
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property billToStreet2 (base name: "billToStreet2")', function() {
      // uncomment below and update the code to test the property billToStreet2
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property billToStreet3 (base name: "billToStreet3")', function() {
      // uncomment below and update the code to test the property billToStreet3
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property billToCity (base name: "billToCity")', function() {
      // uncomment below and update the code to test the property billToCity
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property billToState (base name: "billToState")', function() {
      // uncomment below and update the code to test the property billToState
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property billToZip (base name: "billToZip")', function() {
      // uncomment below and update the code to test the property billToZip
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property billToCountry (base name: "billToCountry")', function() {
      // uncomment below and update the code to test the property billToCountry
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property billToPhone (base name: "billToPhone")', function() {
      // uncomment below and update the code to test the property billToPhone
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property billToEmail (base name: "billToEmail")', function() {
      // uncomment below and update the code to test the property billToEmail
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property orderShipDate (base name: "orderShipDate")', function() {
      // uncomment below and update the code to test the property orderShipDate
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property shippedDate (base name: "shippedDate")', function() {
      // uncomment below and update the code to test the property shippedDate
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property daysInStorage (base name: "daysInStorage")', function() {
      // uncomment below and update the code to test the property daysInStorage
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property freight (base name: "freight")', function() {
      // uncomment below and update the code to test the property freight
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property orderWeightLbs (base name: "orderWeightLbs")', function() {
      // uncomment below and update the code to test the property orderWeightLbs
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property orderEstimatedWeightLbs (base name: "orderEstimatedWeightLbs")', function() {
      // uncomment below and update the code to test the property orderEstimatedWeightLbs
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property numberOfPallets (base name: "numberOfPallets")', function() {
      // uncomment below and update the code to test the property numberOfPallets
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property numberOfLineItems (base name: "numberOfLineItems")', function() {
      // uncomment below and update the code to test the property numberOfLineItems
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property completionStatus (base name: "completionStatus")', function() {
      // uncomment below and update the code to test the property completionStatus
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property holdCode (base name: "holdCode")', function() {
      // uncomment below and update the code to test the property holdCode
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property shipCode (base name: "shipCode")', function() {
      // uncomment below and update the code to test the property shipCode
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property orderMessage (base name: "orderMessage")', function() {
      // uncomment below and update the code to test the property orderMessage
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property division (base name: "division")', function() {
      // uncomment below and update the code to test the property division
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property costCenter (base name: "costCenter")', function() {
      // uncomment below and update the code to test the property costCenter
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property authorizedBy (base name: "authorizedBy")', function() {
      // uncomment below and update the code to test the property authorizedBy
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property batchNo (base name: "batchNo")', function() {
      // uncomment below and update the code to test the property batchNo
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property firstShipDate (base name: "firstShipDate")', function() {
      // uncomment below and update the code to test the property firstShipDate
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property lastShipDate (base name: "lastShipDate")', function() {
      // uncomment below and update the code to test the property lastShipDate
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property deliverOnDate (base name: "deliverOnDate")', function() {
      // uncomment below and update the code to test the property deliverOnDate
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property customerPONo (base name: "customerPONo")', function() {
      // uncomment below and update the code to test the property customerPONo
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property shipVia (base name: "shipVia")', function() {
      // uncomment below and update the code to test the property shipVia
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property needByDate (base name: "needByDate")', function() {
      // uncomment below and update the code to test the property needByDate
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property total (base name: "total")', function() {
      // uncomment below and update the code to test the property total
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property balanceDue (base name: "balanceDue")', function() {
      // uncomment below and update the code to test the property balanceDue
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property totalPaid (base name: "totalPaid")', function() {
      // uncomment below and update the code to test the property totalPaid
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property authorizationAmount (base name: "authorizationAmount")', function() {
      // uncomment below and update the code to test the property authorizationAmount
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property subtotal (base name: "subtotal")', function() {
      // uncomment below and update the code to test the property subtotal
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property taxOnFreight (base name: "taxOnFreight")', function() {
      // uncomment below and update the code to test the property taxOnFreight
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property tax (base name: "tax")', function() {
      // uncomment below and update the code to test the property tax
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property distributionCharges (base name: "distributionCharges")', function() {
      // uncomment below and update the code to test the property distributionCharges
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property shippingCharge (base name: "shippingCharge")', function() {
      // uncomment below and update the code to test the property shippingCharge
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property totalDiscount (base name: "totalDiscount")', function() {
      // uncomment below and update the code to test the property totalDiscount
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property parcelAccountId (base name: "parcelAccountId")', function() {
      // uncomment below and update the code to test the property parcelAccountId
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property thirdPartyParcelAccountId (base name: "thirdPartyParcelAccountId")', function() {
      // uncomment below and update the code to test the property thirdPartyParcelAccountId
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property packingSlipTemplateId (base name: "packingSlipTemplateId")', function() {
      // uncomment below and update the code to test the property packingSlipTemplateId
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property giftMessage (base name: "giftMessage")', function() {
      // uncomment below and update the code to test the property giftMessage
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property branchSector (base name: "branchSector")', function() {
      // uncomment below and update the code to test the property branchSector
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property branchArea (base name: "branchArea")', function() {
      // uncomment below and update the code to test the property branchArea
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property branchCustomerType (base name: "branchCustomerType")', function() {
      // uncomment below and update the code to test the property branchCustomerType
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property branchId (base name: "branchId")', function() {
      // uncomment below and update the code to test the property branchId
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property orderCode (base name: "orderCode")', function() {
      // uncomment below and update the code to test the property orderCode
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property leadPackageId (base name: "leadPackageId")', function() {
      // uncomment below and update the code to test the property leadPackageId
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property totalQty (base name: "totalQty")', function() {
      // uncomment below and update the code to test the property totalQty
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property estimatedNumberOfPicks (base name: "estimatedNumberOfPicks")', function() {
      // uncomment below and update the code to test the property estimatedNumberOfPicks
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property orderConfirmationEmailTemplateId (base name: "orderConfirmationEmailTemplateId")', function() {
      // uncomment below and update the code to test the property orderConfirmationEmailTemplateId
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property shipmentConfirmationEmailTemplateId (base name: "shipmentConfirmationEmailTemplateId")', function() {
      // uncomment below and update the code to test the property shipmentConfirmationEmailTemplateId
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property orderInvoiceTemplateId (base name: "orderInvoiceTemplateId")', function() {
      // uncomment below and update the code to test the property orderInvoiceTemplateId
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property priceMode (base name: "priceMode")', function() {
      // uncomment below and update the code to test the property priceMode
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property warehouseServiceTypeId (base name: "warehouseServiceTypeId")', function() {
      // uncomment below and update the code to test the property warehouseServiceTypeId
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property warehouseServiceLevelId (base name: "warehouseServiceLevelId")', function() {
      // uncomment below and update the code to test the property warehouseServiceLevelId
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property slaDate (base name: "slaDate")', function() {
      // uncomment below and update the code to test the property slaDate
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property slaStatus (base name: "slaStatus")', function() {
      // uncomment below and update the code to test the property slaStatus
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property productionType (base name: "productionType")', function() {
      // uncomment below and update the code to test the property productionType
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property backOrderStatus (base name: "backOrderStatus")', function() {
      // uncomment below and update the code to test the property backOrderStatus
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property backOrderReleaseDate (base name: "backOrderReleaseDate")', function() {
      // uncomment below and update the code to test the property backOrderReleaseDate
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property billingQuantity (base name: "billingQuantity")', function() {
      // uncomment below and update the code to test the property billingQuantity
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property chargedRate (base name: "chargedRate")', function() {
      // uncomment below and update the code to test the property chargedRate
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property extendedCharge (base name: "extendedCharge")', function() {
      // uncomment below and update the code to test the property extendedCharge
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

    it('should have the property customFields (base name: "customFields")', function() {
      // uncomment below and update the code to test the property customFields
      //var instane = new infoplus.OrderLineActivity();
      //expect(instance).to.be();
    });

  });

}));
