/**
 * Infoplus API
 * Infoplus API.
 *
 * OpenAPI spec version: v3.0
 * Contact: api@infopluscommerce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.infoplus);
  }
}(this, function(expect, infoplus) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new infoplus.Gs1128LabelApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Gs1128LabelApi', function() {
    describe('addGs1128LabelAudit', function() {
      it('should call addGs1128LabelAudit successfully', function(done) {
        //uncomment below and update the code to test addGs1128LabelAudit
        //instance.addGs1128LabelAudit(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addGs1128LabelFile', function() {
      it('should call addGs1128LabelFile successfully', function(done) {
        //uncomment below and update the code to test addGs1128LabelFile
        //instance.addGs1128LabelFile(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addGs1128LabelFileByURL', function() {
      it('should call addGs1128LabelFileByURL successfully', function(done) {
        //uncomment below and update the code to test addGs1128LabelFileByURL
        //instance.addGs1128LabelFileByURL(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addGs1128LabelTag', function() {
      it('should call addGs1128LabelTag successfully', function(done) {
        //uncomment below and update the code to test addGs1128LabelTag
        //instance.addGs1128LabelTag(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteGs1128Label', function() {
      it('should call deleteGs1128Label successfully', function(done) {
        //uncomment below and update the code to test deleteGs1128Label
        //instance.deleteGs1128Label(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteGs1128LabelFile', function() {
      it('should call deleteGs1128LabelFile successfully', function(done) {
        //uncomment below and update the code to test deleteGs1128LabelFile
        //instance.deleteGs1128LabelFile(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteGs1128LabelTag', function() {
      it('should call deleteGs1128LabelTag successfully', function(done) {
        //uncomment below and update the code to test deleteGs1128LabelTag
        //instance.deleteGs1128LabelTag(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDuplicateGs1128LabelById', function() {
      it('should call getDuplicateGs1128LabelById successfully', function(done) {
        //uncomment below and update the code to test getDuplicateGs1128LabelById
        //instance.getDuplicateGs1128LabelById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getGs1128LabelByFilter', function() {
      it('should call getGs1128LabelByFilter successfully', function(done) {
        //uncomment below and update the code to test getGs1128LabelByFilter
        //instance.getGs1128LabelByFilter(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getGs1128LabelById', function() {
      it('should call getGs1128LabelById successfully', function(done) {
        //uncomment below and update the code to test getGs1128LabelById
        //instance.getGs1128LabelById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getGs1128LabelFiles', function() {
      it('should call getGs1128LabelFiles successfully', function(done) {
        //uncomment below and update the code to test getGs1128LabelFiles
        //instance.getGs1128LabelFiles(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getGs1128LabelTags', function() {
      it('should call getGs1128LabelTags successfully', function(done) {
        //uncomment below and update the code to test getGs1128LabelTags
        //instance.getGs1128LabelTags(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateGs1128LabelCustomFields', function() {
      it('should call updateGs1128LabelCustomFields successfully', function(done) {
        //uncomment below and update the code to test updateGs1128LabelCustomFields
        //instance.updateGs1128LabelCustomFields(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
