/**
 * Infoplus API
 * Infoplus API.
 *
 * OpenAPI spec version: beta
 * Contact: api@infopluscommerce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.infoplus);
  }
}(this, function(expect, infoplus) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new infoplus.ParcelAccountApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ParcelAccountApi', function() {
    describe('addParcelAccountAudit', function() {
      it('should call addParcelAccountAudit successfully', function(done) {
        //uncomment below and update the code to test addParcelAccountAudit
        //instance.addParcelAccountAudit(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addParcelAccountFile', function() {
      it('should call addParcelAccountFile successfully', function(done) {
        //uncomment below and update the code to test addParcelAccountFile
        //instance.addParcelAccountFile(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addParcelAccountTag', function() {
      it('should call addParcelAccountTag successfully', function(done) {
        //uncomment below and update the code to test addParcelAccountTag
        //instance.addParcelAccountTag(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteParcelAccountTag', function() {
      it('should call deleteParcelAccountTag successfully', function(done) {
        //uncomment below and update the code to test deleteParcelAccountTag
        //instance.deleteParcelAccountTag(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDuplicateParcelAccountById', function() {
      it('should call getDuplicateParcelAccountById successfully', function(done) {
        //uncomment below and update the code to test getDuplicateParcelAccountById
        //instance.getDuplicateParcelAccountById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getParcelAccountByFilter', function() {
      it('should call getParcelAccountByFilter successfully', function(done) {
        //uncomment below and update the code to test getParcelAccountByFilter
        //instance.getParcelAccountByFilter(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getParcelAccountById', function() {
      it('should call getParcelAccountById successfully', function(done) {
        //uncomment below and update the code to test getParcelAccountById
        //instance.getParcelAccountById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getParcelAccountTags', function() {
      it('should call getParcelAccountTags successfully', function(done) {
        //uncomment below and update the code to test getParcelAccountTags
        //instance.getParcelAccountTags(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateParcelAccountCustomFields', function() {
      it('should call updateParcelAccountCustomFields successfully', function(done) {
        //uncomment below and update the code to test updateParcelAccountCustomFields
        //instance.updateParcelAccountCustomFields(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
