/**
 * Infoplus API
 * Infoplus API.
 *
 * OpenAPI spec version: beta
 * Contact: api@infopluscommerce.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.infoplus);
  }
}(this, function(expect, infoplus) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new infoplus.ReplenishmentPlanApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ReplenishmentPlanApi', function() {
    describe('addReplenishmentPlan', function() {
      it('should call addReplenishmentPlan successfully', function(done) {
        //uncomment below and update the code to test addReplenishmentPlan
        //instance.addReplenishmentPlan(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addReplenishmentPlanAudit', function() {
      it('should call addReplenishmentPlanAudit successfully', function(done) {
        //uncomment below and update the code to test addReplenishmentPlanAudit
        //instance.addReplenishmentPlanAudit(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addReplenishmentPlanFile', function() {
      it('should call addReplenishmentPlanFile successfully', function(done) {
        //uncomment below and update the code to test addReplenishmentPlanFile
        //instance.addReplenishmentPlanFile(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addReplenishmentPlanTag', function() {
      it('should call addReplenishmentPlanTag successfully', function(done) {
        //uncomment below and update the code to test addReplenishmentPlanTag
        //instance.addReplenishmentPlanTag(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteReplenishmentPlan', function() {
      it('should call deleteReplenishmentPlan successfully', function(done) {
        //uncomment below and update the code to test deleteReplenishmentPlan
        //instance.deleteReplenishmentPlan(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteReplenishmentPlanTag', function() {
      it('should call deleteReplenishmentPlanTag successfully', function(done) {
        //uncomment below and update the code to test deleteReplenishmentPlanTag
        //instance.deleteReplenishmentPlanTag(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDuplicateReplenishmentPlanById', function() {
      it('should call getDuplicateReplenishmentPlanById successfully', function(done) {
        //uncomment below and update the code to test getDuplicateReplenishmentPlanById
        //instance.getDuplicateReplenishmentPlanById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getReplenishmentPlanByFilter', function() {
      it('should call getReplenishmentPlanByFilter successfully', function(done) {
        //uncomment below and update the code to test getReplenishmentPlanByFilter
        //instance.getReplenishmentPlanByFilter(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getReplenishmentPlanById', function() {
      it('should call getReplenishmentPlanById successfully', function(done) {
        //uncomment below and update the code to test getReplenishmentPlanById
        //instance.getReplenishmentPlanById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getReplenishmentPlanTags', function() {
      it('should call getReplenishmentPlanTags successfully', function(done) {
        //uncomment below and update the code to test getReplenishmentPlanTags
        //instance.getReplenishmentPlanTags(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateReplenishmentPlan', function() {
      it('should call updateReplenishmentPlan successfully', function(done) {
        //uncomment below and update the code to test updateReplenishmentPlan
        //instance.updateReplenishmentPlan(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateReplenishmentPlanCustomFields', function() {
      it('should call updateReplenishmentPlanCustomFields successfully', function(done) {
        //uncomment below and update the code to test updateReplenishmentPlanCustomFields
        //instance.updateReplenishmentPlanCustomFields(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
